object BuildDependenciesVersions {
    const val KOTLIN = "1.6.0"
    const val APPCOMPAT = "1.3.1"
    const val MATERIAL = "1.4.0"
    const val COROUTINES = "1.5.2"
    const val ROOM = "2.3.0"
    const val RECYCLE_VIEW = "1.2.1"
    const val NAVIGATION = "2.3.5"
    const val LIFECYCLE = "2.4.0"
    const val CORE_KTX = "1.7.0"
    const val FRAGMENT_KTX = "1.3.6"
    const val CONSTRAIN_LAYOUT = "2.1.1"
    const val SWIPE_REFRESH_LAYOUT = "1.1.0"
    const val DAGGER = "2.40.1"
    const val TIMBER = "5.0.1"
    const val RETROFIT = "2.9.0"
    const val OKHTTP = "4.9.2"
    const val MOSHI = "1.12.0"
    const val COIL = "1.4.0"
    const val PLAY_CORE = "1.10.0"
    const val LEAKCANARY = "2.7"
    const val ANDROID_SDP = "1.0.6"
    const val ANDROID_SSP = "1.0.6"
    const val DATABINDING = "4.2.2"
    const val MULTIDEX = "2.0.1"
    const val PERMISSION_DISPATCHER = "1.0.5"
    const val DESUGAR_JDK="1.1.5"
    const val EXO_PLAYER_VERSION="2.12.0"
    const val LOCATION="18.0.0"

    // Tests
    const val TEST = "1.3.0"
    const val EXT = "1.1.2"
    const val ARCH_CORE = "2.1.0"
    const val JUNIT = "4.13.2"
    const val ROBOLECTRIC = "4.5.1"
    const val MOCKK = "1.12.0"
    const val ASSERTJ = "3.20.2"
    const val ESPRESSO = "3.3.0"
    const val FRAGMENT_TEST = "1.3.6"
    const val MOCK_WEB_SERVER = "4.9.2"
}
